In [ ]:
# todo: fix cost mistake on diagram

Here's the network we'll be building: 

![](1-1-1_nnet.PNG)

We'll use a sigmoid activation function this time with our backpropagation:

![](1-1-1_nnet_backprop_combined.PNG)

Let's begin.

In [7]:
import numpy as np
from math import e 

In [34]:
# Create some dummy data 
X = np.array([1,2,3,4,5,6,5,4,3,2,1])
Y = np.array([0,0,1,1,1,1,1,1,1,0,0])

# Init weights and biases randomly 
w1 = np.random.random()
w2 = np.random.random()
b1 = np.random.random()
b2 = np.random.random()

step_size = 5
n_epoch = 1000

# Forward pass 
for n in range(n_epoch):
    for i in range(len(X)):
        a0 = X[i]
        y = Y[i]

        def sigmoid(x): return e**x / (e**x + 1)

        # go up the computational graph 
        net1 = a0 * w1 + b1 
        a1 = sigmoid(net1)
        net2 = a1 * w2 + b2 
        a2 = sigmoid(net2)
        Cost = (a2 - y)**2

        # backprop
        dCost_dCost = 1 
        dCost_da2 = 2*(a2 - y) * dCost_dCost 
        dCost_dnet2 = (sigmoid(net2) * (1 - (sigmoid(net2)))) * dCost_da2 
        dCost_da1 = w2 * dCost_dnet2
        dCost_dw2 = a1 * dCost_dnet2 
        dCost_db2 = 1 * dCost_dnet2 
        dCost_dnet1 = (sigmoid(net1) * (1 - (sigmoid(net1)))) * dCost_da1
        dCost_da0 = w1 * dCost_dnet1
        dCost_dw1 = a0 * dCost_dnet1
        dCost_db1 = 1 * dCost_dnet1

        # update weights 
        b1 += step_size * -1 * dCost_db1
        w1 += step_size * -1 * dCost_dw1
        b2 += step_size * -1 * dCost_db2
        w2 += step_size * -1 * dCost_dw2

    
    if n % 200 == 0 :
        print (Cost)
        print(np.array([b1, w1, b2, w2]).round(2))


0.583590850222
[-0.54 -0.05 -0.68  0.22]
9.93628882739e-05
[ 14.69  -5.93   4.52  -9.12]
4.07317420096e-05
[ 14.79  -5.98   4.95 -10.  ]
2.51644552248e-05
[ 14.85  -6.     5.18 -10.48]
1.80654585847e-05
[ 14.89  -6.02   5.34 -10.8 ]


In [35]:
preds = [ sigmoid(w2 *sigmoid(b1 + w1*X[i]) + b2) for i in range(len(X))]

In [36]:
preds

[0.0037466632435566153,
 0.0067801736780517549,
 0.99344351361866645,
 0.99578349174251057,
 0.99578814678201832,
 0.99578815794389164,
 0.99578814678201832,
 0.99578349174251057,
 0.99344351361866645,
 0.0067801736780517549,
 0.0037466632435566153]

In [30]:
Y

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0])